#define SCRIPT2_CORE                        1
#define SCRIPT2_RNG                         2
#define SCRIPT2_ITOS                        3
#define SCRIPT2_FTOS                        4
#define SCRIPT2_SPRINTER                    5
#define SCRIPT2_CLOCK                       6
#define SCRIPT2_STACK                       7
#define SCRIPT2_MATRIX                      8
#define SCRIPT2_STRING                      9
#define SCRIPT2_LOOM                        10
#define SCRIPT2_LIST                        11
#define SCRIPT2_BOOK                        12
#define SCRIPT2_MAP                         13
#define SCRIPT2_TABLE                       14
#define SCRIPT2_DIC                         15
#define SCRIPT2_CRABS                       16
#define SCRIPT2_DOOR                        17
#define SCRIPT2_FILECABINET                 18
// Kabuki Toolkit Seams                  
// Who API                               
#define KABUKITOOLKIT_WHO_ACCOUNT          19 
#define KABUKITOOLKIT_WHO_ADDRESS          20
#define KABUKITOOLKIT_WHO_ADDRESSEMAIL     21
#define KABUKITOOLKIT_WHO_AUTHENTICATOR    22
#define KABUKITOOLKIT_WHO_ENTITY           23
#define KABUKITOOLKIT_WHO_ENTITYGROUP      24
#define KABUKITOOLKIT_WHO_ENTITYLIST       25
#define KABUKITOOLKIT_WHO_HANDLE           26
#define KABUKITOOLKIT_WHO_NAME             27
#define KABUKITOOLKIT_WHO_ORGANIZATION     28
#define KABUKITOOLKIT_WHO_PASSWORD         29
#define KABUKITOOLKIT_WHO_PERSON           30
#define KABUKITOOLKIT_WHO_PRIVILEGE        31
#define KABUKITOOLKIT_WHO_PROFILE          32
#define KABUKITOOLKIT_WHO_REGISTRAR        33
#define KABUKITOOLKIT_WHO_RELATIONSHIP     34
#define KABUKITOOLKIT_WHO_ROLE             35
#define KABUKITOOLKIT_WHO_ROSTER           36
#define KABUKITOOLKIT_WHO_SYMBOL           37
#define KABUKITOOLKIT_WHO_UIDASSIGNER      38
#define KABUKITOOLKIT_WHO_USER             39
#define KABUKITOOLKIT_WHO_USERLIST         40
// Pro API                               
#define KABUKITOOLKIT_PRO_GIT              41
#define KABUKITOOLKIT_PRO_ISSUE            42
#define KABUKITOOLKIT_PRO_MISSION          43
#define KABUKITOOLKIT_PRO_PROJECT          44
#define KABUKITOOLKIT_PRO_SCHEDULE         45
#define KABUKITOOLKIT_PRO_TASK             46
#define KABUKITOOLKIT_PRO_WORKSPACE        47
// Code API
#define KABUKITOOLKIT_CODE_CODEMODULE      48
#define KABUKITOOLKIT_CODE_COMMENTSTRIPPER 49
#define SEAM_N                           